# Generated by Django 5.0.7 on 2024-08-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_rand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='list',
            new_name='listt',
        ),
    ]
